# Generated by Django 5.2.6 on 2025-09-15 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('language', models.TextField()),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='TypeChat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'type_chats',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=15)),
                ('name', models.TextField()),
                ('language', models.ForeignKey(db_column='language', on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='customers.language')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('chat_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('typechat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chats', to='customers.typechat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='customers.user')),
            ],
            options={
                'db_table': 'chats',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['language'], name='USERS_index_0'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['typechat'], name='chat_typechat_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('chat_id', 'typechat')},
        ),
    ]
